---
apiVersion: v2
name: chaoskube
type: application
description: Chaoskube periodically kills random pods in your Kubernetes cluster.
icon: https://raw.githubusercontent.com/linki/chaoskube/master/chaoskube.png
home: https://github.com/linki/chaoskube
keywords:
  - chaos-monkey
  - chaos-engineering
maintainers:
  # TODO: remove Thomas and add linki
  - name: Thomas Gosteli
    email: thomas.gosteli@protonmail.com
    url: https://github.com/ghouscht
version: 0.1.0
appVersion: 0.21.0
